//------------------------------------------------------------------------------
// <auto-generated>
//    This file was generated by the provided buildtools.
//    (Time of creation: 2020-07-12 22:18:33)
//
//    Changes to this file may cause incorrect behavior and will be lost if
//    the code is regenerated.
//
//    This tool was last located at: 'src/Utilities/Buildtools/bin/Release/netcoreapp3.1/'. 
//    The configuration for it is located at: 'src/Utilities/Buildtools.config.json'. 
// </auto-generated>
//------------------------------------------------------------------------------

const YER_TOOLS_UIX_CONFIGURATION = 
{
  "buildTime": "2020-07-12T20:18:33.1424734Z",
  "fileSystem": {
    "path": {
      "jsRootPath": "/js/"
    },
    "fileName": {
      "uix": "UIX.js",
      "ajaxWorker": "UIX.AjaxWorker.js",
      "serviceWorker": "UIX.ServiceWorker.js"
    }
  }
}