/// <reference path="../Helper/ISODateFormat.ts" />

namespace BuildTools.Configuration{

    export function autoGeneratedFileWarning():string{
        
        const timeOfCreation = Helper.ISODateFormat.format(new Date());

        return `//------------------------------------------------------------------------------
// <auto-generated>
//    This file was generated by the provided BuildTools.
//    (Time of creation: ` + timeOfCreation + `)
//
//    Changes to this file may cause incorrect behavior and will be lost if
//    the code is regenerated.
//
//    This tool was last located at: '`+ __filename + `'. 
//    The configuration for it is located at: '` + configPath + `'. 
// </auto-generated>
//------------------------------------------------------------------------------

`;
    }
}