name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install npm dependencies
      run: |
        npm install -g typescript
        npm install -g sass
    - name: Install buildtools dependencies
      run: dotnet restore
      working-directory: ./src/Utilities/Buildtools
    - name: Build buildtools
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src/Utilities/Buildtools
    - name: Run buildtools
      run: dotnet run --configuration Release --no-restore -b
      working-directory: ./src/Utilities/Buildtools
